//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGleason.SpeakFaster.BasicKeyboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamGleason.SpeakFaster.BasicKeyboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CommandKeyRef KeyRef=&quot;Function.Windows&quot; Column=&quot;0&quot;/&gt;
        ///&lt;CommandKeyRef KeyRef=&quot;Function.ExpandHint&quot; Column=&quot;2&quot;/&gt;
        ///&lt;PredictionKeyRef KeyRef=&quot;Predictions.First&quot; ColumnSpan=&quot;2&quot; Column=&quot;3&quot; RowSpan=&quot;1&quot; Row=&quot;0&quot;/&gt;
        ///&lt;PredictionKeyRef KeyRef=&quot;Predictions.Second&quot; ColumnSpan=&quot;2&quot; Column=&quot;5&quot; RowSpan=&quot;1&quot; Row=&quot;0&quot;/&gt;
        ///&lt;PredictionKeyRef KeyRef=&quot;Predictions.Third&quot; ColumnSpan=&quot;2&quot; Column=&quot;7&quot; RowSpan=&quot;1&quot; Row=&quot;0&quot;/&gt;
        ///&lt;CommandKeyRef KeyRef=&quot;Function.MouseLeftClick&quot; Column=&quot;9&quot;/&gt;
        ///&lt;CommandKeyRef KeyRef=&quot;Navigate.Punctuation&quot; ColumnSpa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
    }
}
