//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamGleason.SpeakFaster.BasicKeyboard.Layout.Standard.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamGleason.SpeakFaster.BasicKeyboard.Layout.Standard.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;KeyboardLayout Id=&quot;Control_en-US_Qwerty&quot; Rows=&quot;4&quot; Columns=&quot;12&quot;&gt;
        ///  &lt;Version&gt;
        ///    &lt;Number&gt;4&lt;/Number&gt;
        ///  &lt;/Version&gt;
        ///  &lt;Language&gt;
        ///    &lt;Name&gt;English&lt;/Name&gt;
        ///    &lt;Code&gt;en-US&lt;/Code&gt;
        ///  &lt;/Language&gt;
        ///  &lt;TextKeys&gt;
        ///    &lt;TextKey Id=&quot;a&quot; Label=&quot;a&quot; Text=&quot;a&quot;&gt;
        ///      &lt;Modifiers&gt;
        ///        &lt;Shift KeyRef=&quot;A&quot; /&gt;
        ///        &lt;CapsLock KeyRef=&quot;A&quot; /&gt;
        ///      &lt;/Modifiers&gt;
        ///    &lt;/TextKey&gt;
        ///    &lt;TextKey Id=&quot;b&quot; Label=&quot;b&quot; Text=&quot;b&quot;&gt;
        ///      &lt;Modifiers&gt;
        ///        &lt;Shift KeyRef=&quot;B&quot; /&gt;
        ///        &lt;Caps [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US_Qwerty {
            get {
                return ResourceManager.GetString("en_US_Qwerty", resourceCulture);
            }
        }
    }
}
